---
- name: "configuration play."
  hosts: web
  user: ubuntu
  gather_facts: false
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml

  pre_tasks:
    - name: "install python for Ansible."
      raw: sudo apt-get -y install python

  roles:
    - setup
    - setup_node
    - setup_pm2
