---
- name: "install pm2"
  become: yes
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: Create directory
  file:
    path: ~/web
    state: directory

- name: Copy index page
  template:
    src: "files/index.js"
    dest: "~/web/index.js"

- name: Executing node
  shell: |
    pm2 start ~/web/index.js -f
